"use client";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import {
  RadarChart, Radar, PolarGrid, PolarAngleAxis,
  PolarRadiusAxis, ResponsiveContainer, Tooltip
} from "recharts";
import {
  CheckCircle, XCircle, AlertCircle,
  Download, RotateCcw, Star, Quote
} from "lucide-react";

interface Dimension {
  score: number;
  evidence: string;
}

interface Assessment {
  candidate_name: string;
  recommendation: "PROCEED" | "CONSIDER" | "REJECT";
  overall_score: number;
  summary: string;
  dimensions: {
    communication_clarity: Dimension;
    warmth: Dimension;
    patience: Dimension;
    ability_to_simplify: Dimension;
    english_fluency: Dimension;
  };
  strengths: string[];
  concerns: string[];
  interviewer_notes: string;
}

const DIMENSION_LABELS: Record<string, string> = {
  communication_clarity: "Clarity",
  warmth: "Warmth",
  patience: "Patience",
  ability_to_simplify: "Simplicity",
  english_fluency: "Fluency",
};

const RECOMMENDATION_CONFIG = {
  PROCEED: {
    icon: CheckCircle,
    color: "text-green-400",
    bg: "bg-green-400/10 border-green-400/30",
    glow: "shadow-green-500/20",
    label: "Proceed to Next Round",
    emoji: "✅",
  },
  CONSIDER: {
    icon: AlertCircle,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10 border-yellow-400/30",
    glow: "shadow-yellow-500/20",
    label: "Consider with Review",
    emoji: "⚠️",
  },
  REJECT: {
    icon: XCircle,
    color: "text-red-400",
    bg: "bg-red-400/10 border-red-400/30",
    glow: "shadow-red-500/20",
    label: "Not Recommended",
    emoji: "❌",
  },
};

const getScoreColor = (score: number) => {
  if (score >= 8) return "text-green-400";
  if (score >= 6) return "text-yellow-400";
  return "text-red-400";
};

const getScoreBg = (score: number) => {
  if (score >= 8) return "bg-green-400";
  if (score >= 6) return "bg-yellow-400";
  return "bg-red-400";
};

export default function ReportPage() {
  const router = useRouter();
  const [assessment, setAssessment] = useState<Assessment | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<"overview" | "details" | "transcript">("overview");
  const [transcript, setTranscript] = useState("");

  useEffect(() => {
    const result = localStorage.getItem("assessment_result");
    const savedTranscript = localStorage.getItem("interview_transcript");

    if (result) {
      setAssessment(JSON.parse(result));
      setTranscript(savedTranscript || "");
    }
    setLoading(false);
  }, []);

  const handleDownload = () => {
    if (!assessment) return;

    const content = `
CUEMATH AI TUTOR SCREENER — ASSESSMENT REPORT
══════════════════════════════════════════════════

Candidate: ${assessment.candidate_name}
Date: ${new Date().toLocaleDateString("en-IN", {
      day: "numeric", month: "long", year: "numeric"
    })}
Recommendation: ${assessment.recommendation}
Overall Score: ${assessment.overall_score}/10

SUMMARY
───────────────────────────────────────────────
${assessment.summary}

DIMENSION SCORES
───────────────────────────────────────────────
Communication Clarity : ${assessment.dimensions.communication_clarity.score}/10
Warmth               : ${assessment.dimensions.warmth.score}/10
Patience             : ${assessment.dimensions.patience.score}/10
Ability to Simplify  : ${assessment.dimensions.ability_to_simplify.score}/10
English Fluency      : ${assessment.dimensions.english_fluency.score}/10

EVIDENCE
───────────────────────────────────────────────
Clarity   : "${assessment.dimensions.communication_clarity.evidence}"
Warmth    : "${assessment.dimensions.warmth.evidence}"
Patience  : "${assessment.dimensions.patience.evidence}"
Simplicity: "${assessment.dimensions.ability_to_simplify.evidence}"
Fluency   : "${assessment.dimensions.english_fluency.evidence}"

STRENGTHS
───────────────────────────────────────────────
${assessment.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}

CONCERNS
───────────────────────────────────────────────
${assessment.concerns.map((c, i) => `${i + 1}. ${c}`).join("\n")}

INTERVIEWER NOTES
───────────────────────────────────────────────
${assessment.interviewer_notes}

FULL TRANSCRIPT
───────────────────────────────────────────────
${transcript}

══════════════════════════════════════════════════
Generated by Cuemath AI Tutor Screener
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${assessment.candidate_name.replace(/\s+/g, "_")}_Cuemath_Assessment.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen gradient-bg flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 rounded-full bg-gradient-to-br from-purple-500 to-orange-400 flex items-center justify-center mx-auto mb-4 speaking-animation">
            <span className="text-white text-2xl font-bold">M</span>
          </div>
          <p className="text-gray-400">Generating assessment report...</p>
        </div>
      </div>
    );
  }

  if (!assessment) {
    return (
      <div className="min-h-screen gradient-bg flex items-center justify-center">
        <div className="text-center glass rounded-2xl p-8">
          <p className="text-gray-400 mb-4">No assessment found.</p>
          <button
            onClick={() => router.push("/")}
            className="bg-purple-600 text-white px-6 py-2 rounded-xl"
          >
            Start New Interview
          </button>
        </div>
      </div>
    );
  }

  const config = RECOMMENDATION_CONFIG[assessment.recommendation];
  const RecommendIcon = config.icon;

  const radarData = Object.entries(assessment.dimensions).map(([key, val]) => ({
    dimension: DIMENSION_LABELS[key],
    score: val.score,
    fullMark: 10,
  }));

  return (
    <div className="min-h-screen gradient-bg">
      {/* Header */}
      <header className="p-4 glass flex items-center justify-between sticky top-0 z-10">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-purple-600 flex items-center justify-center">
            <Star size={16} className="text-white fill-white" />
          </div>
          <span className="font-bold text-white">Cuemath</span>
          <span className="text-gray-500 text-sm">· Assessment Report</span>
        </div>
        <div className="flex items-center gap-2">
          <motion.button
            onClick={handleDownload}
            whileTap={{ scale: 0.95 }}
            className="flex items-center gap-2 glass px-4 py-2 rounded-xl text-gray-300 hover:text-white text-sm transition-colors"
          >
            <Download size={14} />
            Download
          </motion.button>
          <motion.button
            onClick={() => router.push("/")}
            whileTap={{ scale: 0.95 }}
            className="flex items-center gap-2 bg-purple-600 hover:bg-purple-500 px-4 py-2 rounded-xl text-white text-sm transition-colors"
          >
            <RotateCcw size={14} />
            New Interview
          </motion.button>
        </div>
      </header>

      <div className="max-w-5xl mx-auto p-6 space-y-6">

        {/* Hero Card */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className={`glass rounded-2xl p-8 border shadow-2xl ${config.bg} ${config.glow}`}
        >
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div>
              <p className="text-gray-400 text-sm mb-1">Assessment for</p>
              <h1 className="text-3xl font-bold text-white mb-1">
                {assessment.candidate_name}
              </h1>
              <p className="text-gray-400 text-sm">
                {new Date().toLocaleDateString("en-IN", {
                  day: "numeric", month: "long", year: "numeric"
                })} · Cuemath AI Tutor Screener
              </p>
            </div>

            <div className="flex flex-col items-center md:items-end gap-3">
              {/* Overall Score */}
              <div className="flex items-center gap-3">
                <div className="text-right">
                  <div className={`text-5xl font-bold ${getScoreColor(assessment.overall_score)}`}>
                    {assessment.overall_score}
                    <span className="text-xl text-gray-500">/10</span>
                  </div>
                  <div className="text-gray-400 text-xs">Overall Score</div>
                </div>
              </div>

              {/* Recommendation Badge */}
              <div className={`flex items-center gap-2 px-5 py-2 rounded-full border ${config.bg}`}>
                <RecommendIcon size={18} className={config.color} />
                <span className={`font-semibold text-sm ${config.color}`}>
                  {config.label}
                </span>
              </div>
            </div>
          </div>

          {/* Summary */}
          <div className="mt-6 glass rounded-xl p-4">
            <p className="text-gray-300 text-sm leading-relaxed italic">
              &quot;{assessment.summary}&quot;
            </p>
          </div>
        </motion.div>

        {/* Tabs */}
        <div className="flex gap-2">
          {(["overview", "details", "transcript"] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-5 py-2 rounded-xl text-sm font-medium capitalize transition-all
                ${activeTab === tab
                  ? "bg-purple-600 text-white"
                  : "glass text-gray-400 hover:text-white"}`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Tab: Overview */}
        {activeTab === "overview" && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid grid-cols-1 md:grid-cols-2 gap-6"
          >
            {/* Radar Chart */}
            <div className="glass rounded-2xl p-6">
              <h3 className="text-white font-semibold mb-4">
                Performance Radar
              </h3>
              <ResponsiveContainer width="100%" height={280}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="rgba(255,255,255,0.1)" />
                  <PolarAngleAxis
                    dataKey="dimension"
                    tick={{ fill: "#9CA3AF", fontSize: 12 }}
                  />
                  <PolarRadiusAxis
                    domain={[0, 10]}
                    tick={{ fill: "#6B7280", fontSize: 10 }}
                  />
                  <Radar
                    name="Score"
                    dataKey="score"
                    stroke="#8B5CF6"
                    fill="#8B5CF6"
                    fillOpacity={0.3}
                    strokeWidth={2}
                  />
                  <Tooltip
                    contentStyle={{
                      background: "#1A1A2E",
                      border: "1px solid rgba(255,255,255,0.1)",
                      borderRadius: "8px",
                      color: "white",
                    }}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </div>

            {/* Score Bars */}
            <div className="glass rounded-2xl p-6">
              <h3 className="text-white font-semibold mb-4">
                Dimension Scores
              </h3>
              <div className="space-y-4">
                {Object.entries(assessment.dimensions).map(([key, val]) => (
                  <div key={key}>
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-gray-300 text-sm">
                        {DIMENSION_LABELS[key]}
                      </span>
                      <span className={`font-bold text-sm ${getScoreColor(val.score)}`}>
                        {val.score}/10
                      </span>
                    </div>
                    <div className="h-2 bg-white/10 rounded-full overflow-hidden">
                      <motion.div
                        className={`h-full rounded-full ${getScoreBg(val.score)}`}
                        initial={{ width: 0 }}
                        animate={{ width: `${(val.score / 10) * 100}%` }}
                        transition={{ duration: 0.8, delay: 0.1 }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Strengths */}
            <div className="glass rounded-2xl p-6">
              <h3 className="text-green-400 font-semibold mb-4 flex items-center gap-2">
                <CheckCircle size={18} /> Strengths
              </h3>
              <ul className="space-y-2">
                {assessment.strengths.map((s, i) => (
                  <li key={i} className="flex items-start gap-2 text-gray-300 text-sm">
                    <div className="w-5 h-5 rounded-full bg-green-400/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-green-400 text-xs font-bold">{i + 1}</span>
                    </div>
                    {s}
                  </li>
                ))}
              </ul>
            </div>

            {/* Concerns */}
            <div className="glass rounded-2xl p-6">
              <h3 className="text-red-400 font-semibold mb-4 flex items-center gap-2">
                <AlertCircle size={18} /> Areas of Concern
              </h3>
              <ul className="space-y-2">
                {assessment.concerns.length > 0
                  ? assessment.concerns.map((c, i) => (
                    <li key={i} className="flex items-start gap-2 text-gray-300 text-sm">
                      <div className="w-5 h-5 rounded-full bg-red-400/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                        <span className="text-red-400 text-xs font-bold">{i + 1}</span>
                      </div>
                      {c}
                    </li>
                  ))
                  : <p className="text-gray-500 text-sm">No major concerns noted.</p>}
              </ul>
            </div>
          </motion.div>
        )}

        {/* Tab: Details */}
        {activeTab === "details" && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            {Object.entries(assessment.dimensions).map(([key, val]) => (
              <div key={key} className="glass rounded-2xl p-6">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-white font-semibold">
                    {DIMENSION_LABELS[key]}
                  </h3>
                  <div className={`text-2xl font-bold ${getScoreColor(val.score)}`}>
                    {val.score}
                    <span className="text-sm text-gray-500">/10</span>
                  </div>
                </div>
                <div className="h-1.5 bg-white/10 rounded-full mb-4">
                  <motion.div
                    className={`h-full rounded-full ${getScoreBg(val.score)}`}
                    initial={{ width: 0 }}
                    animate={{ width: `${(val.score / 10) * 100}%` }}
                    transition={{ duration: 0.6 }}
                  />
                </div>
                <div className="flex items-start gap-2 glass rounded-xl p-3">
                  <Quote size={14} className="text-purple-400 flex-shrink-0 mt-0.5" />
                  <p className="text-gray-300 text-sm italic">{val.evidence}</p>
                </div>
              </div>
            ))}

            {/* Interviewer Notes */}
            <div className="glass rounded-2xl p-6 border border-purple-500/20">
              <h3 className="text-purple-400 font-semibold mb-3">
                🔒 Interviewer Notes (Internal)
              </h3>
              <p className="text-gray-300 text-sm leading-relaxed">
                {assessment.interviewer_notes}
              </p>
            </div>
          </motion.div>
        )}

        {/* Tab: Transcript */}
        {activeTab === "transcript" && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass rounded-2xl p-6"
          >
            <h3 className="text-white font-semibold mb-4">
              Full Interview Transcript
            </h3>
            <div className="space-y-3">
              {transcript
                ? transcript.split("\n\n").map((line, i) => {
                  const isMaya = line.startsWith("Maya:");
                  return (
                    <div
                      key={i}
                      className={`rounded-xl p-3 text-sm ${
                        isMaya
                          ? "bg-purple-600/10 border border-purple-500/20"
                          : "bg-white/5"
                      }`}
                    >
                      <span className={`font-semibold ${isMaya ? "text-purple-400" : "text-orange-400"}`}>
                        {line.split(":")[0]}:{" "}
                      </span>
                      <span className="text-gray-300">
                        {line.split(":").slice(1).join(":").trim()}
                      </span>
                    </div>
                  );
                })
                : <p className="text-gray-500">No transcript available.</p>}
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}